[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
uefi_bootloader = { path = ".." }
panic-halt = "0.2.0"
log = {version = "*", default-features = false }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"