[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-default_settings.json"

[target.'cfg(target_os = "none")']
runner = "./package_kernel_and_run.py"
